[package]
name = "gitfetch"
version = "0.1.0"
edition = "2024"

[dependencies]
octocrab = { version = "0.44.1"}
tokio = { version = "1.46.1", features = ["full"] }
serde_json = "1.0.140"
serde = "1.0.219"
